### PR TITLE
[BLDKCMF-19] Resolve RDK Compliance Issues

### PR DESCRIPTION
**Pull request by TeknoVenus**
Various changes to comply with RDK licensing and resolve Blackduck issues.

Copyright headers changed from 
```
"Copyright 2020 RDK Management"
```
to
```
"Copyright <Year> Sky UK"
```

Added missing headers where appropriate. Other minor changes to address compliance issues.

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Steve,
Thank you for the impressive turnaround on a lot of files!  Here are a few places which still need attention:

Two Copyrights:
./AppInfrastructure/Common/test/source/Boolean_gtest.cpp
./AppInfrastructure/Common/test/source/ISO8601Test.cpp
./AppInfrastructure/Common/test/source/VersionNumberTest.cpp
./AppInfrastructure/Common/source/Timer.cpp
./AppInfrastructure/Public/Common/Interface.h
./daemon/process/sky-dobby.service
./daemon/init/source/InitMain.cpp

Correct License File name:
: "If not stated otherwise in this file or this component's license file the..." -replace with "...LICENSE file..."
(There are 55 of these, just use grep to locate rather than pasting the list here.)
Agreed this is a fussy point but we are trying to get this consistent across all of RDK.

Missed one file:
rdkcentral/Dobby//develop/vagrant/Vagrantfile

Sorry, I missed this while doing the scan: in README.md, line 281 rename "Licenses.txt" -> LICENSE

Thanks,
Martin

**Comment by mhughesacn** [comment]
Hi Stephen,

Thank you for making the changes.  Just two small fixes that were missed:
1. AppInfrastructure/IpcService/test/build/component.mk line 1: ("license file" - "LICENSE file")
and
2. Please change LICENSE line 189 to use the generic form exactly as follows:
Copyright [yyyy] [name of copyright owner]

I will set about clearing the issues in the tools so Dobby commits should normally be compliance clean.

Thanks,

Martin

**Comment by TeknoVenus** [comment]
Hi Martin,

Just want to clarify what you mean for point 2 as line 189 of LICENSE currently reads:
```
   Copyright 2020 Sky UK
```

This already seems to be in the generic form of `Copyright [yyyy] [owner]`. I'm not sure what it should be changed to?

Thanks.

**Comment by mhughesacn** [comment]
Hi Stephen,
What I want is exactly:
Copyright [yyyy] [name of copyright owner]
meaning this exact text and no mention of a real year or Sky UK.
There's a long story around this usage and it's not a big deal here where there is only one codebase which is Apache licensed.  But often people copy one component's LICENSE as a start, so it may as well be right now from the get-go.
Thanks,
Martin

**Pull request merged**
