### PR TITLE
 [RDK-43928] DobbyManager Mock Class Modification

### PR DESCRIPTION
**Pull request by Prathyushakothuru**
### Description
correcting the mock files used for the  implementation of DobbyManager Test API's

### Test Procedure
NA

### Type of Change
- [ ] New feature (non-breaking change which adds functionality)

### Requires Bitbake Recipe changes?
- yes

### CODE REVIEW

**Review by goruklu — APPROVED** [review]

**Review by goruklu — CHANGES_REQUESTED** [review]
builds are failing

**Comment by goruklu** [comment]
@Prathyushakothuru can you please fix the build errors ?

**Comment by Prathyushakothuru** [comment]
> @Prathyushakothuru can you please fix the build errors ?

**Comment by Prathyushakothuru** [comment]
Fixed the build failures, can you please check it now

**Comment by goruklu** [comment]
@Prathyushakothuru still seeing build errors, please check

**Review by goruklu — APPROVED** [review]

**Pull request merged**
