### PR TITLE
[RDK-46381] Fix the networking and command_line_containers related is…

### PR DESCRIPTION
**Pull request by KaleeswaranGnanagurusamy**
### Description
Changes done:
1. Coverage report added
2. DNS resolver change in vagrant file for wget command failure
3. created the separate mount spec config files for GitHub VM and vagrant VM test.
4. Added new platform enum for github_workflow_vm.
5. Added "rbind" option for etc alternatives path in network1 bundle.
6. Added the network interfaces in "dobby.dev_vm.json" file for the GitHub VM test.
7. Removed Networking type field in sleepy-thunder_bundle config.json, and added the start_from_bundle and thuder_plugin tests in runner.py
8. Fixed  SyntaxWarning: "is" with 'str' literal. Did you mean "==" in bundle_generation.py

If there is a corresponding JIRA ticket, please ensure it is in the title of the PR.

### Test Procedure
1. Run in vagrant setup
2. Run in GitHub workflow.

### Type of Change
- [ ]  L2 test enhancement

### Requires Bitbake Recipe changes?
- [ ] NA

### CODE REVIEW

**Comment by goruklu** [comment]
Is there a reason for handling GithubVM and VagrantVM seperately ? They are both Ubuntu VMs so we should be able to use the same VM environment I think.

**Comment by KaleeswaranGnanagurusamy** [comment]
> Is there a reason for handling GithubVM and VagrantVM seperately ? They are both Ubuntu VMs so we should be able to use the same VM environment I think.

**Comment by KaleeswaranGnanagurusamy** [comment]
The mounts test in the command_line_containers test suite fails in GitHub due to a "mounts: source path mismatch" (which is indicated in the mounts-vm.json file as "source": "/home/vagrant/srcDobby/tests/test_runner/files") since this path is unavailable when the test is executed in GitHub.

In place of the vagrant path, we have generated a second JSON file called mounts-github-workflow-vm.json and specified the GitHub path there. while running the test from GitHub, we use mounts-github-workflow-vm.json; while running it from Vagrant, we use mounts-vagrant-vm.json. hence we've introduced a new GitHub platform.

**Comment by goruklu** [comment]
@KaleeswaranGnanagurusamy can you please rebase and fix the conflicts ?

**Comment by KaleeswaranGnanagurusamy** [comment]
> @KaleeswaranGnanagurusamy can you please rebase and fix the conflicts ?

Resolved the conflicts

**Review by goruklu — APPROVED** [review]

**Pull request merged**
