### PR TITLE
[RDK-43927] Dobby Unit Test

### PR DESCRIPTION
**Pull request by sethulakshmisk**
### Description
: Folder architecture change for configure the unit test Build
   { internal files are moved into an include directory to facilitate unit testing by allowing creation of mock header files in a separate directory}
: Extra mock classes have been added for Dobby Unit Test
   {As of now, we've focused on correcting the mock files used for the implemented Dobby Test APIs. The remaining mock files will be addressed as a separate task}

### Test Procedure
NA

### Type of Change
- [x] New feature (non-breaking change which adds functionality)

### Requires Bitbake Recipe changes?
-yes

### CODE REVIEW

**Review by goruklu — APPROVED** [review]

**Comment by mhughesacn** [comment]
Hi,
Where do the new files come from - would expect Sky copyrights in this component usually?  i.e. If from Sky or its contractors, or Synamedia if this is a Synamedia contribution.
- Martin Hughes, RDK CMF Compliance Team

**Comment by goruklu** [comment]
> Hi, Where do the new files come from - would expect Sky copyrights in this component usually? i.e. If from Sky or its contractors, or Synamedia if this is a Synamedia contribution.
> 
> * Martin Hughes, RDK CMF Compliance Team
@mhughesacn 
The changes are coming from the Synamedia team. Should we change the copyrights from "RDK management" to "Sky" or "Synamedia" ?

**Comment by mhughesacn** [comment]
Hi @goruklu : Suggest that Synamedia copyright be used if it is Synamedia code i.e. not written as contractors to Sky.  If using Synamedia, please add a two-liner to NOTICE:
_Copyright 2023 Synamedia
Licensed under the Apache License, Version 2.0_
I will clear off any failing checks.
Thank you!

**Comment by sethulakshmisk** [comment]
> Hi @goruklu : Suggest that Synamedia copyright be used if it is Synamedia code i.e. not written as contractors to Sky. If using Synamedia, please add a two-liner to NOTICE: _Copyright 2023 Synamedia Licensed under the Apache License, Version 2.0_ I will clear off any failing checks. Thank you!

Hi @mhughesacn and @goruklu , 
As suggested, changed the copyright of all the newly added files to 
Copyright 2023 Synamedia
Licensed under the Apache License, Version 2.0
Kindly check and approve.
Thanks.

**Review by goruklu — APPROVED** [review]

**Comment by goruklu** [comment]
@mhughesacn can you please check? We added the two lines you suggested, still seeing blackduck scan failures, thanks!

**Comment by mhughesacn** [comment]
Hi @sethulakshmisk , @goruklu
Thanks for making the changes. Please update the NOTICE as I asked (Oct 27).  I have cleared the copyright and will do Blackduck when the credit in NOTICE is inserted.
(Apologies for the delay - yesterday was a holiday here.)

**Comment by goruklu** [comment]
@sethulakshmisk can you please add 
"Copyright 2023 Synamedia
Licensed under the Apache License, Version 2.0"
in the NOTICE file ?

**Comment by sethulakshmisk** [comment]
> @sethulakshmisk can you please add "Copyright 2023 Synamedia Licensed under the Apache License, Version 2.0" in the NOTICE file ?

Hi @goruklu and @mhughesacn  , 
Added the information in NOTICE File. Please approve
Thank you!

**Review by goruklu — APPROVED** [review]

**Pull request merged**
